name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "💥 Breaking Changes"
    labels:
      - "breaking"
      - "breaking-change"
  - title: "✨ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "⚡ Performance"
    labels:
      - "performance"
  - title: "🔒 Security"
    labels:
      - "security"
  - title: "📦 Dependencies"
    labels:
      - "dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - "breaking"
      - "breaking-change"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "fix"
      - "bugfix"
      - "bug"
      - "patch"
      - "chore"
      - "maintenance"
      - "docs"
      - "documentation"
      - "dependencies"
  default: patch

template: |
  ## 🚀 Changes in v$RESOLVED_VERSION

  $CHANGES

  ## 🐳 Docker Image
  The Docker image is available at: `j4v3l/tapo-exporter:v$RESOLVED_VERSION`

  ## 🛠️ Installation
  ```bash
  docker pull j4v3l/tapo-exporter:v$RESOLVED_VERSION
  ```

  **Full Changelog**: https://github.com/j4v3l/tapo/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
